### ISSUE TITLE
Trouble running radiance benchmark on debian

### ISSUE THREAD

**Issue by himadrics** [markstock/Radiance-Benchmark4#1]
Hi,

I'm a researcher at INRIA, Paris and I am interested in testing radiance benchmark with our new scheduler policy. I am trying to compile and run the benchmark with phoronix-test-suite version 10.4.0 on an x86 machine running with Debian 11. Phoronix fails to run the benchmark with "The test quit with a non-zero exit status." error and I am unable to find any crashlogs. When I try to coplile the souce manually I get the following error:

me@mymachine:~/.phoronix-test-suite/installed-tests/pts/radiance-1.0.0/Radiance-Benchmark4-master# make all
/bin/sh: 1: genbox: not found
/bin/sh: 1: rpict: not found
/bin/sh: 1: rpict: not found
obj2mesh -n 15 -r 16384 lens.obj > lens.msh
/bin/sh: 1: obj2mesh: not found
make: *** [Makefile:70: scene.oct] Error 127

I tried to find Debian packages "obj2mesh" and "radiance" but no luck so far. I can really use some help in making this benchmark work on my machine. Thanks in advance :).

**Comment by markstock** [comment]
I had no idea the tests were being used by phoronix. The benchmark test relies on a current installation of Radiance, which may not be readily available in Debian (it is not in Fedora - I always manually install it).

Are you able to download and install Radiance locally? If so, add the `bin` directory to PATH and the `lib` directory to RAYPATH and the benchmarks should work.

You've reminded me that I should add some better error messages to the script.
